baseURL = 'https://hungvnprocessingdev.click/'
languageCode = 'en-us'
title = 'Xưởng Thực Thi'
theme = 'ananke'

[[menu.main]]
    name = "services"
    url = "/services/"
    weight = 1

[[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 4

[[menu.main]]
    name = "privacy"
    url = "/privacy/"
    weight = 5